# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - develop

resources:
  - repo: self

variables:
  imageName: 'test'

stages:
  - stage: Build
    displayName: Build and push Docker image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - script: |
              echo "Extracting version from package.json"
              VERSION_NUMBER=$(grep '"version"' package.json | sed -E 's/.*"([^"]+)".*/\1/')
              echo "Version: $VERSION_NUMBER"
              echo "##vso[task.setvariable variable=versionNumber]$VERSION_NUMBER"

          - task: Docker@2
            displayName: Build and push
            inputs:
              containerRegistry: DockerhubService
              repository: 'danvoidll/$(imageName)'
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              command: 'buildAndPush'
              tags: $(versionNumber)
